-- MODULO FISCAL: Emissao de Nota (NFS)
-- Data: 2026-04-12

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'InvoiceStatus') THEN
    CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT', 'ISSUED', 'CANCELED');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "Invoice" (
  "id"                 TEXT NOT NULL DEFAULT gen_random_uuid()::text,
  "invoiceNumber"      INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "series"             TEXT NOT NULL DEFAULT 'NFS',
  "status"             "InvoiceStatus" NOT NULL DEFAULT 'ISSUED',
  "serviceOrderId"     TEXT NOT NULL,
  "clientId"           TEXT NOT NULL,
  "contractId"         TEXT,
  "issueDate"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dueDate"            TIMESTAMP(3),
  "description"        TEXT,
  "grossAmount"        DECIMAL(12, 2) NOT NULL,
  "discountAmount"     DECIMAL(12, 2) NOT NULL DEFAULT 0,
  "taxAmount"          DECIMAL(12, 2) NOT NULL DEFAULT 0,
  "netAmount"          DECIMAL(12, 2) NOT NULL,
  "externalReference"  TEXT,
  "canceledAt"         TIMESTAMP(3),
  "cancellationReason" TEXT,
  "createdById"        TEXT,
  "issuedById"         TEXT,
  "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_invoiceNumber_key" ON "Invoice"("invoiceNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_serviceOrderId_key" ON "Invoice"("serviceOrderId");
CREATE INDEX IF NOT EXISTS "Invoice_status_issueDate_idx" ON "Invoice"("status", "issueDate");
CREATE INDEX IF NOT EXISTS "Invoice_clientId_issueDate_idx" ON "Invoice"("clientId", "issueDate");
CREATE INDEX IF NOT EXISTS "Invoice_contractId_idx" ON "Invoice"("contractId");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Invoice_serviceOrderId_fkey'
  ) THEN
    ALTER TABLE "Invoice"
      ADD CONSTRAINT "Invoice_serviceOrderId_fkey"
      FOREIGN KEY ("serviceOrderId") REFERENCES "ServiceOrder"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Invoice_clientId_fkey'
  ) THEN
    ALTER TABLE "Invoice"
      ADD CONSTRAINT "Invoice_clientId_fkey"
      FOREIGN KEY ("clientId") REFERENCES "Client"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Invoice_contractId_fkey'
  ) THEN
    ALTER TABLE "Invoice"
      ADD CONSTRAINT "Invoice_contractId_fkey"
      FOREIGN KEY ("contractId") REFERENCES "Contract"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Invoice_createdById_fkey'
  ) THEN
    ALTER TABLE "Invoice"
      ADD CONSTRAINT "Invoice_createdById_fkey"
      FOREIGN KEY ("createdById") REFERENCES "User"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Invoice_issuedById_fkey'
  ) THEN
    ALTER TABLE "Invoice"
      ADD CONSTRAINT "Invoice_issuedById_fkey"
      FOREIGN KEY ("issuedById") REFERENCES "User"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
