export const REPOSITORY_TOKENS = {
  USERS_REPOSITORY: Symbol('USERS_REPOSITORY'),
  CLIENTS_REPOSITORY: Symbol('CLIENTS_REPOSITORY'),
  SERVICE_ORDERS_REPOSITORY: Symbol('SERVICE_ORDERS_REPOSITORY')
} as const;
