import axios, { type AxiosInstance } from 'axios';
import { PrismaClient } from '@prisma/client';

type LoginResponse = {
  accessToken: string;
  refreshToken: string;
};

const prisma = new PrismaClient();

function logStep(step: string, detail: string): void {
  console.log(`[${step}] ${detail}`);
}

async function buildApiClient(baseURL: string): Promise<AxiosInstance> {
  const api = axios.create({
    baseURL,
    timeout: 30000
  });

  const loginResponse = await api.post<LoginResponse>('/auth/login', {
    email: 'admin@oms.local',
    password: 'Admin@123'
  });

  api.defaults.headers.common.Authorization = `Bearer ${loginResponse.data.accessToken}`;
  return api;
}

async function run(): Promise<void> {
  const apiPrefix = process.env.API_PREFIX ?? 'api/v1';
  const apiBaseURL = process.env.API_BASE_URL ?? `http://localhost:3000/${apiPrefix}`;
  const unique = Date.now().toString();

  logStep('INIT', `API base URL ${apiBaseURL}`);

  const anonymousApi = axios.create({ baseURL: apiBaseURL, timeout: 30000 });
  const health = await anonymousApi.get('/health');
  logStep('HEALTH', JSON.stringify(health.data));

  const api = await buildApiClient(apiBaseURL);
  logStep('AUTH', 'Login success for admin@oms.local');

  const [clientCount, orderCount, invoiceCount] = await Promise.all([
    api.get('/clients?page=1&limit=100'),
    api.get('/service-orders?page=1&limit=100'),
    api.get('/invoices?page=1&limit=100')
  ]);

  logStep(
    'BASELINE',
    `clients=${clientCount.data.meta.total} orders=${orderCount.data.meta.total} invoices=${invoiceCount.data.meta.total}`
  );

  const createdClient = await api.post('/clients', {
    type: 'BUSINESS',
    name: `Cliente Integracao ${unique}`,
    legalName: `Cliente Integracao ${unique} LTDA`,
    taxId: `7711223300${unique.slice(-4)}`,
    email: `integracao-${unique}@demo.local`,
    phone: '65999123456',
    contactName: 'Responsavel Integracao',
    addresses: [
      {
        label: 'Matriz',
        street: 'Avenida Integracao',
        number: '100',
        district: 'Centro',
        city: 'Cuiaba',
        state: 'MT',
        zipCode: '78000000',
        isPrimary: true
      }
    ]
  });
  logStep('CLIENT', `created clientId=${createdClient.data.id}`);

  const [serviceType, team, technician] = await Promise.all([
    prisma.serviceType.findFirst({
      where: { active: true },
      select: { id: true }
    }),
    prisma.team.findFirst({
      where: { active: true },
      select: { id: true }
    }),
    prisma.user.findFirst({
      where: { status: 'ACTIVE', deletedAt: null },
      select: { id: true }
    })
  ]);

  if (!serviceType || !team || !technician) {
    throw new Error('Required catalog data not found: serviceType/team/technician');
  }

  const scheduledStart = new Date(Date.now() + 60 * 60 * 1000).toISOString();
  const scheduledEnd = new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString();

  const createdOrder = await api.post('/service-orders', {
    clientId: createdClient.data.id,
    serviceTypeId: serviceType.id,
    assignedTeamId: team.id,
    assignedTechnicianId: technician.id,
    title: `OS Integracao ${unique}`,
    description: 'Fluxo completo de demonstracao',
    priority: 'HIGH',
    scheduledStartAt: scheduledStart,
    scheduledEndAt: scheduledEnd
  });
  logStep('SERVICE_ORDER', `created orderId=${createdOrder.data.id} status=${createdOrder.data.status}`);

  await api.post(`/service-orders/${createdOrder.data.id}/transition-status`, {
    toStatus: 'IN_TRANSIT',
    reason: 'Demo transition to transit'
  });
  await api.post(`/service-orders/${createdOrder.data.id}/transition-status`, {
    toStatus: 'IN_PROGRESS',
    reason: 'Demo transition to in progress'
  });
  await api.post(`/service-orders/${createdOrder.data.id}/check-in`, {
    at: new Date().toISOString()
  });
  await api.post(`/service-orders/${createdOrder.data.id}/check-out`, {
    at: new Date().toISOString()
  });
  const completedOrder = await api.get(`/service-orders/${createdOrder.data.id}`);
  logStep('WORKFLOW', `order completed with status=${completedOrder.data.status}`);

  const emittedInvoice = await api.post('/invoices/emit', {
    serviceOrderId: createdOrder.data.id,
    grossAmount: 2500,
    discountAmount: 100,
    taxAmount: 300,
    description: 'Invoice generated by full demo flow'
  });
  logStep('INVOICE', `emitted invoice=${emittedInvoice.data.displayNumber} id=${emittedInvoice.data.id}`);

  const invoiceDetail = await api.get(`/invoices/${emittedInvoice.data.id}`);
  logStep('INVOICE_DETAIL', `status=${invoiceDetail.data.status} netAmount=${invoiceDetail.data.netAmount}`);

  const triage = await api.post('/operations-tools/basic/triage-score', {
    impact: 4,
    urgency: 5,
    effortHours: 6
  });
  const checklist = await api.post('/operations-tools/basic/checklist-template', {
    serviceCategory: 'PREVENTIVE'
  });
  const slaPlan = await api.post('/operations-tools/intermediate/sla-plan', {
    openedAt: new Date().toISOString(),
    responseTargetHours: 4,
    resolutionTargetHours: 24
  });
  const balancing = await api.post('/operations-tools/intermediate/workload-balancing', {
    technicians: [
      {
        id: 'tech-1',
        name: 'Tech 1',
        skills: ['network'],
        currentLoadHours: 8,
        weeklyCapacityHours: 40
      },
      {
        id: 'tech-2',
        name: 'Tech 2',
        skills: ['network', 'field'],
        currentLoadHours: 12,
        weeklyCapacityHours: 40
      }
    ],
    workOrders: [
      {
        id: 'os-1',
        requiredSkills: ['network'],
        estimatedHours: 6,
        priority: 5
      },
      {
        id: 'os-2',
        requiredSkills: ['field'],
        estimatedHours: 4,
        priority: 3
      }
    ]
  });
  const routePlan = await api.post('/operations-tools/advanced/route-plan', {
    startLatitude: -15.601,
    startLongitude: -56.097,
    averageSpeedKmh: 35,
    stops: [
      { id: 'os-1', latitude: -15.602, longitude: -56.098, serviceMinutes: 30 },
      { id: 'os-2', latitude: -15.603, longitude: -56.099, serviceMinutes: 45 }
    ]
  });
  const risk = await api.post('/operations-tools/advanced/risk-estimation', {
    backlogSize: 20,
    overdueCount: 4,
    avgResolutionHours: 18,
    reopenRatePercent: 8,
    firstTimeFixRatePercent: 82,
    teamAvailabilityPercent: 76
  });
  logStep(
    'OPERATIONS_TOOLS',
    `triage=${triage.data.priority} checklistItems=${checklist.data.checklist?.length ?? 0} risk=${risk.data.level}`
  );

  const [dashboard, reports, notifications, audit, orderContext, invoices] = await Promise.all([
    api.get('/dashboard/overview'),
    api.get('/reports/dashboard'),
    api.get('/notifications/me'),
    api.get('/audit-logs?page=1&limit=20'),
    api.get(`/service-orders/${createdOrder.data.id}/context`),
    api.get('/invoices?page=1&limit=20')
  ]);

  logStep('DASHBOARD', `cards=${Object.keys(dashboard.data ?? {}).length}`);
  logStep('REPORTS', `keys=${Object.keys(reports.data ?? {}).length}`);
  logStep('NOTIFICATIONS', `items=${notifications.data.items?.length ?? notifications.data.length ?? 0}`);
  logStep('AUDIT', `items=${audit.data.items?.length ?? 0}`);
  logStep('CONTEXT', `dynamicFields=${orderContext.data.dynamicFields?.length ?? 0}`);
  logStep('INVOICES_LIST', `total=${invoices.data.meta.total}`);

  console.log('FULL_FLOW_DEMO_OK=true');
}

run()
  .catch((error: unknown) => {
    console.error('FULL_FLOW_DEMO_OK=false');
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
